name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CHECK: "check.sh"
  REPORTS: "coding-style-reports.log"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Build source code"
        run: make

  coding-style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Execute coding style"
        run: $CHECK $(pwd) $(pwd)
        working-directory: src
      - name: "Check the coding style"
        # RES=$(cat $REPORTS | grep -v "C-G1" | grep -v "C-L" | grep -v "C-H" | wc -l)
        run: |
          RES=$(cat $REPORTS | grep -v "C-G1" | grep -v "C-L" | wc -l)
          cat $REPORTS | grep -v "C-G1" | grep -v "C-L"
          if [[ ${RES} -gt 3 ]]; then
            echo "::error:: Too many Coding-Style errors..."
            exit 1
          fi
        working-directory: src
